### ISSUE TITLE
[Feature Request] Support single dash long names

### ISSUE THREAD

**Issue by novabyte** [rust-lang-nursery/getopts#17]
I'm trying to port an old C application to Rust at the moment. All of the options look like `-stop`; I can't find an argument parsing library in Rust which supports this format. It'd be great if `getopts` could support this legacy argument style for compatibility with old applications where that style is still required.

**Comment by tromey** [comment]
I have a patch for this, but with two caveats.

First, it would be convenient for me if the fix for issue #23 went in first, as the patch for this mode also affects the usage output.

Second, it seemed odd to me to allow "long" options consisting of a single letter, even in the ordinary mode.  And, because it was also convenient for the implementation of this patch, I chose to just disallow them.  That is, things like `optopt` now include:

```
        let long_len = long_name.len();
        assert!(long_len == 0 || long_len > 1);
```

I'm wondering if that seems acceptable.

Without this check I think another pass would be needed to ensure that the options are self-consistent; that is, that the user doesn't specify a short `-a` in one spot and a "long" `-a` in another.

You can see the WIP patch here: https://github.com/tromey/getopts/tree/long-options-only
