### ISSUE TITLE
[discuss] special argument group

### ISSUE THREAD

**Issue by yodalee** [rust-lang-nursery/getopts#43]
When using getopts to write rust coreutils, I encounter this problem.
In `chmod` command, there is arguments like `chmod -x file` or `chmod -0700 file`, which will cause getopts return `UnrecognizedOption`
Of course we can add string "01234567rwx" into optflag, but that is quite weird because they are not expected to show up in opt.usage.
I'm not quite sure how getopts should be modified to deal with this situation.

**Comment by tromey** [comment]
One idea that comes to mind is to let the getopts user provide a function that is called when an option is not recognized.  Another idea would be to provide a mode where unrecognized options are treated as "free" arguments.

**Comment by KodrAus** [comment]
There are definitely some limitations in `getopts` that keep the library targeted at very simple use-cases. For anything more complex you're probably better off looking at `clap`.

Since it's been a while I'll go ahead and close this one as out-of-scope, but if anyone has anything new to add please feel free to re-open!
